branches:
  except:
  - dev
  - /[0-9].+[0-9]_([a-z]|[A-Z])*[0-9]*/
language: c
matrix:
  include:
  - name: linux-x64
    os: linux
    dist: bionic
    env: EXTRA_FLAGS='target_cpu="x64"'
addons:
  apt:
    packages:
      - subversion 
      - ccache 
      - texlive 
      - texlive-fonts-extra 
      - texlive-latex-extra
      - libomp-dev
      - libx11-dev

script:
  - sudo apt build-dep r-base -y
  - wget "${ICCDL}" -q
  - tar xzf intel.tar.gz
  - export PATH=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/bin/:$PATH
  - export INTEL_LICENSE_FILE=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/
  - export MKLROOT=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/mkl/
  - export _intel_cc_opt=" -O3 -fPIC -m64 -march=native -fp-model precise -fp-model source -I${MKLROOT}/include"
  - source /home/travis/build/MitsuhaMiyamizu/R-MKL/intel/bin/compilervars.sh intel64
  - export CC="icc"
  - export CXX="icpc"
  - export F77="ifort"
  - export FC="ifort"
  - export AR="xiar"
  - export LD="xild"
  - export _intel_arch=intel64
  - export _intel_lib=mkl_intel_lp64
  - export _gfortran_lib=mkl_gf_lp64
# - export CFLAGS="-openmp -O3 -ipo -xHost -multiple-processes"
# - export CFLAGS="-O3 -fPIC -m64 -march=native -fp-model precise -fp-model source -I ${MKLROOT}/include"
# - export CXXFLAGS="-openmp -O3 -ipo -xHost -multiple-processes"
# - export FFLAGS="-openmp -O3 -ipo -xHost -multiple-processes"
# - export FCFLAGS="-openmp -O3 -ipo -xHost -multiple-processes"
  - export CFLAGS="${_intel_cc_opt}"
  - export CXXFLAGS="${_intel_cc_opt}"
  - export FFLAGS="${_intel_cc_opt}"
  - export FCFLAGS="${_intel_cc_opt}"
  - ./configure  --prefix=/usr --libdir=/usr/lib --sysconfdir=/etc/R --datarootdir=/usr/share rsharedir=/usr/share/R/ rincludedir=/usr/include/R/ rdocdir=/usr/share/doc/R/ --with-x --with-blas="${_mkllibs}" --with-lapack --enable-R-shlib LIBnn=lib
# - export MKL="-lmkl_rt"
# - export MAIN_LDFLAGS="-openmp"
# - ./configure --with-blas="$MKL" --with-lapack --with-tcltk
  - make
#  - sudo -E env "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" env "PATH=$PATH" make install
