branches:
  only:
  - master
#  - /[0-9].+[0-9]_([a-z]|[A-Z])*[0-9]*/
language: c
  #jobs:
  #include:
  #- name: linux-x64
  #  os: linux
  #  dist: bionic
arch: amd64
os: linux
dist: bionic
addons:
  apt:
    packages:
      - subversion 
      - ccache 
      - texlive 
      - texlive-fonts-extra 
      - texlive-latex-extra
      - libomp-dev
      - libx11-dev
      - libpcre2-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libxmu-dev
      - libxt-dev

script:
  - sudo apt -qq build-dep r-base -y
  - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  - sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  - sudo apt -qq update
  - sudo apt -qq install intel-mkl-2020.0-088
  - wget "${ICCDL}" -q
  - tar xzf intel.tar.gz
  - export PATH=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/bin/:$PATH
  - export INTEL_LICENSE_FILE=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/
# - export MKLROOT=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/mkl/
  - source /opt/intel/mkl/bin/mklvars.sh intel64
# - export PATH=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/bin/:$PATH
# - export INTEL_LICENSE_FILE=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/
# - export MKLROOT=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/mkl/
# - export _intel_cc_opt=" -O3 -fPIC -m64 -march=native -fp-model precise -fp-model source -I${MKLROOT}/include"
  - export MKL="-L${MKLROOT}/lib/intel64 -Wl,--as-needed -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lpthread -lm -ldl"
  - export _gcc_opt=" -O3 -m64 -fopenmp -march=native"
  - export LDFLAGS=" -fopenmp"
  - export CFLAGS="${_gcc_opt} -I${MKLROOT}/include"
  - export CXXFLAGS="${_gcc_opt} -I${MKLROOT}/include"
  - export FFLAGS="${_gcc_opt} -I${MKLROOT}/include"
  - export FCFLAGS="${_gcc_opt} -I${MKLROOT}/include"
  - export CC="icc"
  - export CXX="icpc"
  - export F77="ifort"
  - export FC="ifort"
  - export AR="xiar"
  - export LD="xild"
  - export _intel_arch=intel64
  - export _intel_lib=mkl_intel_lp64
#  - export LD_LIBRARY_PATH=/opt/intel/lib/intel64
  - export LD_LIBRARY_PATH=/home/travis/build/MitsuhaMiyamizu/R-MKL/intel/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel64_lin/
#  - export _gfortran_lib=mkl_gf_lp64
  - source /home/travis/build/MitsuhaMiyamizu/R-MKL/intel/bin/compilervars.sh ${_intel_arch}
#  - source ${MKLROOT}/bin/mklvars.sh ${_intel_arch}
# - source ${MKLROOT}/../bin/ifortvars.sh ${_intel_arch}
# - export _mkllibs=" -L${MKLROOT}/lib/${_intel_arch} -l${_intel_lib} -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl"
#  - export _mkllibs="-L${MKLROOT}/lib/{_intel_arch} -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_gf_lp64.a ${MKLROOT}/lib/intel64/libmkl_gnu_thread.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -l${_intel_lib} -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl"
#  - export _gcc_opt=" -O3 -m64 -fopenmp -march=native"
#  - export LDFLAGS="-fopenmp"
#  - export CFLAGS="${_gcc_opt} -I${MKLROOT}/include"
#  - export CXXFLAGS="${_gcc_opt} -I${MKLROOT}/include"
#  - export FFLAGS="${_gcc_opt} -I${MKLROOT}/include"
#  - export FCFLAGS="${_gcc_opt} -I${MKLROOT}/include"
#  - export FFLAGS="${_intel_cc_opt}"
#  - export FCFLAGS="${_intel_cc_opt}"
# - export CFLAGS="${_intel_cc_opt}"
# - export CXXFLAGS="${_intel_cc_opt}"
# - export LDFLAGS="-fopenmp"
#  - export R_OPENMP_CFLAGS="-fopenmp"
#  - export SHLIB_OPENMP_CFLAGS="-fopenmp"
#  - export SHLIB_OPENMP_CXXFLAGS="-fopenmp"
#  - export SHLIB_OPENMP_FFLAGS="-fopenmp"
#  - export FLIBS=" -lgfortran -lifcore -lifport"
  - wget "https://cran.r-project.org/src/base/R-4/R-4.0.2.tar.gz" -q
  - tar zxf R-4.0.2.tar.gz
  - cd R-4.0.2/
  - sed -i '/^#undef HAVE_MATHERR/d' src/include/config.h.in
  - ./configure --prefix=/usr --libdir=/usr/lib --sysconfdir=/etc/R --datarootdir=/usr/share rsharedir=/usr/share/R/ rincludedir=/usr/include/R/ rdocdir=/usr/share/doc/R/ --with-x --enable-R-shlib --with-blas="$MKL" --with-lapack
  - make
  - sudo -E env "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" env "PATH=$PATH" make install
  - ldd /usr/lib/R/lib/libR.so 
  - cd .. && tar cvf R-4.0.2.tar.gz R-4.0.2/
  - ls -al
#  - source ~/.bashrc
  - Rscript R-benchmark.R
  - Rscript dgemm.R
deploy:
    provider: releases
    token: ${api_key}
    file: R-4.0.2.tar.xz
    skip_cleanup: true
    file_glob: true
    prerelease: true
    draft: true
    on:
      tags: true
      all_branches: true
      repo: MitsuhaMiyamizu/R-MKL
